# Generated by Django 3.2.3 on 2021-05-17 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHoardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_level', models.IntegerField(default=0)),
                ('max_level', models.IntegerField(default=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHoardRollTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_roll', models.IntegerField()),
                ('max_roll', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoardtier')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoardtier')),
            ],
        ),
    ]
