# Generated by Django 3.2.3 on 2021-05-17 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField(default=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='ArtObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=10, default=1.0, max_digits=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('value', models.IntegerField(default=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='GemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHoardGemRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('gem_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.gemgroup')),
                ('treasure_hoard_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoardrolltable')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHoardCoinRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.coin')),
                ('treasure_hoard_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoardrolltable')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHoardArtObjectRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('art_object_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.artobjectgroup')),
                ('treasure_hoard_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoardrolltable')),
            ],
        ),
        migrations.CreateModel(
            name='GemTreasureHoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.gem')),
                ('treasure_hoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoard')),
            ],
        ),
        migrations.CreateModel(
            name='GemGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_roll', models.IntegerField()),
                ('max_roll', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.gem')),
                ('gem_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.gemgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CoinTreasureHoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.coin')),
                ('treasure_hoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoard')),
            ],
        ),
        migrations.CreateModel(
            name='ArtObjectTreasureHoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('art_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.artobject')),
                ('treasure_hoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.treasurehoard')),
            ],
        ),
        migrations.CreateModel(
            name='ArtObjectGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_roll', models.IntegerField()),
                ('max_roll', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('art_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.artobject')),
                ('art_object_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.artobjectgroup')),
            ],
        ),
    ]
