# Generated by Django 3.2.3 on 2021-05-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0003_auto_20210517_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
