# Generated by Django 3.2.3 on 2021-05-21 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0004_contentsource_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('space', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('playable', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.contentsource')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cr', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('is_legendary', models.BooleanField(default=False)),
                ('ac', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('monster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.monstertype')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.race')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.creaturesize')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.contentsource')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.monstersubtype')),
            ],
        ),
    ]
