# Generated by Django 3.2.3 on 2021-05-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0005_creaturesize_monster_monstersubtype_monstertype_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worldgen.race'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worldgen.contentsource'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worldgen.monstersubtype'),
        ),
        migrations.AlterField(
            model_name='race',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worldgen.contentsource'),
        ),
    ]
