# Generated by Django 3.2.3 on 2021-05-25 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0010_alter_location_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
            ],
        ),
        migrations.AddField(
            model_name='locationtype',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='LocationRollTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.locationtype')),
                ('roll_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.rolltable')),
            ],
        ),
    ]
