# Generated by Django 3.2.3 on 2021-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0011_auto_20210525_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrolltableentry',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
